name: Mechanics
main: net.betterverse.mechanics.Mechanics
version: 1.0
authors: [Betterverse]
permissions:
  mechanics.*:
    default: op
    children:
      mechanics.bridge: true
      mechanics.door: true
      mechanics.gate: true
      mechanics.lift: true